# all paths are relative to the project root directory
# rust section can be removed for C++-only project and vice-versa

[cpp]
path = "cpp"
# compiler can be set to: gcc, clang, msvc, clang-cl
compiler = "clang"
use_ninja = true
shared_libs = false

[rust]
path = "rust"

[test]
path = "your_test_script.py"
