# all paths are relative to the project root directory
# rust section can be removed for C++-only project and vice-versa

[cpp]
path = "cpp"
# select suitable profile from tooling/conan_profiles
profile = "tooling/conan_profiles/windows_ninja_msvc"

[rust]
path = "rust"

[test]
path = "your_test_script.py"
