# all paths are relative to the project root directory
# rust section can be removed for cmake-only project and vice-versa

[cmake]
path = "cpp"
# compiler can be set to: gcc, clang, msvc, clang-cl
compiler = "clang"
use_ninja = true
shared_libs = false
# targets per the first argument of add_library or add_executable
targets = [ "all" ]

[rust]
path = "rust"
features = [ "" ]

[migration]
legacy_build = true

[test]
path = "your_test_script.py"
